#exception
'''
name exception
zero division
value exception
index exception
key exception
file exception
'''
#exception handling functions
'''
try
except
finally
else
raise
assert'''  #throws
try:
    a=int(input("Enter the a values"))
    b=int(input("Enter the b values"))
    c=a/b
    print("value of c:",a/b)
except Exception:
  print(" a value is not mentioned")
  print("After exception")

